server:
  port: 80
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/lemorning;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-test
  jpa:
    hibernate:
      ddl-auto: create  # 이 옵션은 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다
      # show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: real
server:
  port: 8082
---
property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c